version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: prompt-db
    environment:
      POSTGRES_USER: promptuser
      POSTGRES_PASSWORD: promptpass
      POSTGRES_DB: promptdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chatai-network

volumes:
  pgdata:

networks:
  chatai-network:
    external: true